### ISSUE TITLE
 fails with NBC 

### ISSUE THREAD

**Issue by 3052** [fdciabdul/Frida-Multiple-Bypass#1]
com.nbcuni.nbc

**Comment by fdciabdul** [comment]
@3052 nope .. its work

![image](https://github.com/fdciabdul/Frida-Multiple-Bypass/assets/31664438/724e8a1e-de4e-4af0-9138-23624ab1b747)


tested in Redmi 9a (dandelion) rooted

**Comment by 3052** [comment]
I am using MITM proxy

**Comment by fdciabdul** [comment]
> I am using MITM proxy

try using [HTTP Toolkit](https://httptoolkit.com/) , no need setup for certificate in device

**Comment by 3052** [comment]
I prefer MITM proxy, it does not require purchase for premium features

**Comment by fdciabdul** [comment]
i know @3052
